# File location: ~/.conf/mpd/mpd.conf

# Database
db_file			"~/.config/mpd/database"

# Log file
log_file		"syslog"

# Music Directory
music_directory		"~/Music"

# Auto refresh DB
auto_update		"yes"

restore_paused "yes"

# Running MPD on an IPC socket instead of the network stack
bind_to_address "127.0.0.1"

# Misc
playlist_directory	"~/.config/mpd/playlists"
pid_file		"~/.config/mpd/pid"
state_file		"~/.local/state/mpd/state"
sticker_file		"~/.config/mpd/sticker.sql"

# Ouput config
audio_output {
	type	"pipewire"
	name	"PipeWire Sound Server"
}
